/**
 * @description       : Class to where you can find all hard-coded values.
 * @group             : 
 * @last modified on  :  24/02/2023
 * @last modified by  :  Shajinder Singh
 * Modifications Log 
 * Ver   Date         Author                                            Modification
 * 1.O   24/02/2023   Shajinder Singh                                   Intial version.
 **/
public with sharing class ConstantsObject {

    //Pricebooks Names
    public final static String STANDARD_PRICEBOOK = 'Standard Price Book';
    public final static String MONTHLY_SUBSCRIPTION = 'Monthly subscription';
    
    //Not applicacble value
    public final static String NOT_APPLICABLE = 'N/a';

    //Country codes
    public final static String SPAIN_COUNTRY_CODE = 'ES';

    //Currency Iso Code
    public final static String EUR_ISO_CODE = 'EUR';



}